### ISSUE TITLE
Project is not starting

### ISSUE THREAD

**Issue by Messhias** [Luisparf/Todo_list#1]
As per readme.md on first attempt of ```docker-compose up -d``` we get the following error:
<img width="1438" alt="Screenshot 2022-01-06 at 11 10 23" src="https://user-images.githubusercontent.com/1161283/148374071-6fbafc2c-51e8-4a84-a4ba-21f05c8df943.png">

Did you forget to commit your docker files?

**Comment by Messhias** [comment]
@Luisparf I managed to execute the command.

But...
<img width="1437" alt="Screenshot 2022-01-06 at 12 56 18" src="https://user-images.githubusercontent.com/1161283/148386332-bad9be57-59b0-46ec-88fb-cecb1b4c48d4.png">


It's not a port error, but there's something wrong with this Dockerfile.

**Comment by Luisparf** [comment]
Hi! I am sorry for the inconvenience. I already updated the repository.
Please, try again.

Em qui., 6 de jan. de 2022 às 09:56, Fabio William Conceição <
***@***.***> escreveu:

**Comment by Luisparf** [comment]
I tested the code into another PC and for me its perfecly functional, but if you have another issue, please tell me. Again sorry for the inconvenience and thanks for the attention!
